import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Banner from '../components/Banner';
import Modal from '../components/Modal';
import SubPlans from '../components/SubPlans';
import { useRecoilValue } from 'recoil';
import { modalState } from '../atoms/modalAtom';
import requests from '../utils/requests';
import { Movie } from '../typings';
import Row from '../components/Row';
import useAuth from '../customHooks/useAuth';
import { getProducts, Product } from '@stripe/firestore-stripe-payments';
import payments from '../lib/stripe';

interface Props {
  // netflixOriginals of type Movie - typings.d.ts
  netflixOriginals: Movie[];
  trendingNow: Movie[];
  topRated: Movie[];
  actionMovies: Movie[];
  comedyMovies: Movie[];
  horrorMovies: Movie[];
  romanceMovies: Movie[];
  documentaries: Movie[];
  // import type interface from firebase-stripe package
  products: Product[];
}

const Home = ({
  netflixOriginals,
  actionMovies,
  comedyMovies,
  documentaries,
  horrorMovies,
  romanceMovies,
  topRated,
  trendingNow,
  products,
}: Props) => {
  const { logout, loading } = useAuth();
  const showModal = useRecoilValue(modalState);
  const subscription = false;

  if (loading || subscription === null) return null;

  // content protection
  if (!subscription) return <SubPlans products={products} />;

  return (
    <div className='relative h-screen bg-gradient-to-b'>
      <Head>
        <title>Netflix Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* Header */}
      <Header />
      <main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
        {/* Banner */}
        <Banner netflixOriginals={netflixOriginals} />
        <section className='md:space-y-20'>
          {/* Movie Rows */}
          <Row title='Top Rated' movies={topRated} />
          <Row title='Trending Now' movies={trendingNow} />
          {/* MyList Component */}
          <Row title='Action/Thrillers' movies={actionMovies} />
          <Row title='Comedies' movies={comedyMovies} />
          <Row title='Horror' movies={horrorMovies} />
          <Row title='Romance' movies={romanceMovies} />
          <Row title='Docmentaries' movies={documentaries} />
        </section>
      </main>
      {/* Modal */}
      {showModal && <Modal />}
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  // get products from firebase/stripe
  const products = await getProducts(payments, {
    includePrices: true,
    activeOnly: true,
  })
    .then((res) => res)
    .catch((error) => console.log(error.message));

  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    // promise.all to avoid individual awaits due to many requests
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);

  // need to return props for serverside rendering
  // https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props
  return {
    props: {
      // fetch requests return id & results objects
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
      products,
    },
  };
};
